"""eltwelveth migration

Revision ID: 78aa3d187c43
Revises: b32a3e99a01b
Create Date: 2019-04-23 15:02:55.858322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78aa3d187c43'
down_revision = 'b32a3e99a01b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pitches', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pitches', type_='foreignkey')
    op.drop_column('pitches', 'user_id')
    # ### end Alembic commands ###
