"""ntenth migration

Revision ID: 935addfae431
Revises: f6f89b05c055
Create Date: 2019-04-23 13:30:11.676270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '935addfae431'
down_revision = 'f6f89b05c055'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('pitches_user_id_fkey', 'pitches', type_='foreignkey')
    op.drop_column('pitches', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('pitches_user_id_fkey', 'pitches', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
