"""ntenth migration

Revision ID: b32a3e99a01b
Revises: 935addfae431
Create Date: 2019-04-23 13:37:18.996355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b32a3e99a01b'
down_revision = '935addfae431'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_comments_username', table_name='comments')
    op.drop_column('comments', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('username', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_index('ix_comments_username', 'comments', ['username'], unique=False)
    # ### end Alembic commands ###
