"""ninth migration

Revision ID: f6f89b05c055
Revises: 9027a04512ce
Create Date: 2019-04-23 13:23:00.663162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6f89b05c055'
down_revision = '9027a04512ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('username', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_comments_username'), 'comments', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comments_username'), table_name='comments')
    op.drop_column('comments', 'username')
    # ### end Alembic commands ###
